name: "チケット作成用"
description: "目的と完了条件を記述するテンプレート"
title: ""
labels: []
body:
  - type: textarea
    id: template
    attributes:
      label: 🎯 目的と完了条件
      description: このIssueの目的と完了条件を記述してください
      value: |
        ## 🎯 目的
        （ここに目的を記入）

        ## ✅ 完了条件
        - [ ] （完了条件その1）
        - [ ] （完了条件その2）
    validations:
      required: true

